-Além do método resolve, há o método reject
-Que é quando determinada lógica não satisfaz nosso programa
então podemos ir para outra com o reject em vez do resolve
-Resolve e reject terminam a promisse ou seja, não podemos chamar mais o then



function verificarNumero(num){
    return new Promise((resolve, reject) =>{
        if(num == 2){
            resolve(console.log(`o numero é ${num} `))
        } else{
            reject(new Error("Falhou"))
        }
    })

}

verificarNumero(2)
verificarNumero(3)